spring.application.name=REST

server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/routesphere_learning}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}

jwt.secret=${JWT_SECRET:HakeioaHnekaMbeajoem-KmansVsnajeiMkS}
jwt.expiration=${JWT_EXPIRATION:3600000}

resend.api.key=${RESEND_API_KEY:re_XV94q8Yq_AfFgiBvpnaVVTwBDKkrukHKS}
resend.from=${RESEND_FROM:RouteSphere <noreply@abhiram.tech>}
spring.devtools.restart.enabled=false
server.forward-headers-strategy=framework
logging.level.root=INFO
logging.level.com.RouteSphere=DEBUG
