spring.application.name=REST

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/routesphere_learning
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=HakeioaHnekaMbeajoem-KmansVsnajeiMkS
jwt.expiration=3600000

resend.api.key=re_XV94q8Yq_AfFgiBvpnaVVTwBDKkrukHKS
resend.from=RouteSphere <noreply@abhiram.tech>
spring.devtools.restart.enabled=false

logging.level.root=INFO
logging.level.com.RouteSphere=DEBUG